### ISSUE TITLE
{chordsize} doesn't affect [*note] annotations, {textsize} doesn't affect comments

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#142]
Using {chordsize} directive in song doesn't affect small annotations marked with asterisk, e.g. [*note].
Using {textsize} directive in song doesn't affect comment sizes.

**To Reproduce**
1. Process attached .cho file, which includes 60% scaling for {textsize} and {chordsize}, using default config 
2. Observe that annotations haven't scaled, nor have comments (but labels have)

**Expected behavior**
Expect that asterisk annotations scale like chords (because annotation maps to chord font spec)
_Might_ expect comments to scale down, like text (but may be an enhancement, because comment font spec is defined separately)

**Sample files and screenshots**
[Typesize_Test.cho.txt](https://github.com/ChordPro/chordpro/files/6421448/Typesize_Test.cho.txt)
[Typesize_Test (scaled).pdf](https://github.com/ChordPro/chordpro/files/6421449/Typesize_Test.scaled.pdf)
[Typesize_Test (unscaled).pdf](https://github.com/ChordPro/chordpro/files/6421450/Typesize_Test.unscaled.pdf)

**Please complete the following information:**
 - OS: Debian Bullseye
 - Perl version v5.32.1
 - ChordPro version 0.978
 - Where did you get ChordPro from: CPAN

**Additional context**
The annotation issue seems like a bug, the comment one may be an enhancement (possible {commentsize} directive?).

Personally, I use this mostly for whole songs, to help fit to one page (e.g. for multiple songs in a book), so a feature to uniformly scale all body (but not header) content proportionately for the current song might address that need better than multiple directives for each different font usage. I'm pretty sure that would be an enhancement, though!

**Comment by sciurius** [comment]
> Expect that asterisk annotations scale like chords (because annotation maps to chord font spec)

Annotations map to the annotations font, which _initially_ defaults to the chords font. 'Initially' means that at the start of the chordpro run the annotations font is copied from the chords font unless it has been specified otherwise. When the song is processed the defaults have been set and {chordsize} only affects chords.

When the chords font is modified in the config file, or on the command line, this _will_ affect the annotations.

As for the comments, as you already noticed, comments and lyrics are separate so setting one doesn't change the other.

The suggestion to 'scale' a song makes sense but I'm not sure what would be the best way to do this. Usually tweaking a bottom margin or linespace in the config file is sufficient to make a song fit.

**Comment by AnniePerson** [comment]
MobileSheets does a good job in scaling a song as a whole: there's a button "Auto-Size Font" that sets the lyrics font size so that no lyrics line gets an additional line break. The fonts for title, chords and so on are scaled similarly. This is at least a good starting point for further manual tweaking.

**Comment by gwyndaf** [comment]
Thanks @sciurius - it's useful to understand how the font mapping works. I've managed a workaround by setting my comment and annotation font size a bit smaller, so they work with my regular config, but don't look out of place when textsize and chordsize are scaled down slightly. 

I appreciate that it's probably against the descriptive nature of the markup to have too many prescriptive directives for output styling, and that's best left to the the configs. I suppose there could be multiple configs for different sizes, but it could get cumbersome. Perhaps a more elegant approach might be a command-line option to scale everything or just song body (not titles/headers or footer), e.g. `--scaleall=80%` or `--scalebody=80%`. Really neat would be to scale (down?) to a max. number of pages (e.g.` --fitpages=1`), but I guess that might be quite complex to realise.

Those wouldn't specifically address my scenario (multiple songs within a single source file), but that might be a niche case, and maybe better solved by judicious editing! I know I could join a folder full of individually-scaled PDFs, but really like the CSV export for a whole 'songbook' file.

Should I close this issue as a bug report, or leave it open as a possible enhancement?

**Comment by gwyndaf** [comment]
@AnniePerson Thanks, yes I use MSP too (though still favour ChordPro's greater stylistic control and chord diagrams for generating PDFs). I think MPS's display settings are maybe analogous to a per-file config, held in its database (rather than special directives in source text). There might be something useful in how their auto-size works, but the database probably makes per-file settings easier to accommodate than with ChordPro.

**Comment by sciurius** [comment]
There is an (undocumented) feature that allows tweaking some settings 'on the fly'. For example:
````
{t Tweaking spacing}
{+pdf.spacing.lyrics 1}

As the [D]deer pants for the [A]water
As the deer pants for the water
As the [D]deer pants for the [A]water
As the deer pants for the water
````

Experience had taught me that a slight change in the lyrics (and/or chords) spacing helps solving almost all cases of songs that just not fit the page.

**Note** This `{+...}` feature currently does not work for _all_ config settings.

Also in the works are song-specific config files, where each song can have its own config settings/adjustments.

Also in the works is a simpler way to change config settings, so that you can write
````
pdf.spacing.lyrics: 1
````
instead of
````
{ "pdf" : 
  { "spacing" : 
    { "lyrics": 1
    }
  }
}
````

**Comment by gwyndaf** [comment]
Ah, thank you: that's really useful for occasional tweaks. I now realise the textsize and chordsize directives are from legacy chordii spec, rather than meant for detailed output styling. The {+ feature looks ideal for limited adjustment, but per-song configs will be ideal: if they could be indicated in the --filelist input, that would allow songs to be merged into a PDF songbook, with per-song formatting, and a metadata sidecar CSV!

I'll close this issue then, as it sounds like you've already got the relevant enhancements on the roadmap.
