### ISSUE TITLE
Files compile individually, but not as songbook

### ISSUE THREAD

**Issue by jzbor** [ChordPro/chordpro#190]
## Describe the bug
I have a bunch of chordpro files and want to make a songbook out of it.
Unfortunately I get an error, when trying to compile them all together.
Interestingly though compiling works for all files individually.  
I can send you the files and my corresponding Makefile by mail, if you need them to reproduce the bug.

### Steps To Reproduce
If you have my files:
1. `make standalone` => works
2. `make saitensprung.pdf` (the songbook) => doesn't work
    * This uses the following command: `chordpro --verbose --config config.json -o $@ $(shell find Lieder -name '*.cho' -printf '"%p" ')`

### Expected behavior
If it compiles the files individually it should compile them together as a songbook as well right?

### Attachments
[output.txt](https://github.com/ChordPro/chordpro/files/7576444/output.txt)

## System information
 - OS: up-to-date Arch Linux x86_64
 - Where did you get ChordPro from? AUR (`chordpro-git`)
 - ChordPro version: 5.985
 - Perl version: v5.34.0

**Comment by sciurius** [comment]
Yes, please send the Makefile + songs. Probably you can reproduce the issue when using just a couple of songs instead of all of them>

**Comment by jzbor** [comment]
I sent all my files to [info@chordpro.org].

**Comment by sciurius** [comment]
Thanks. Nice workflow, my compliments!

The problem happens when ChordPro has to create a table of contents. I could reproduce it with two songs only.

Your config (`config-template.json`) seems to be a copy of an older version and is missing some settings. In particular:

- `"instrument"` is `null`. This should be set to a valid instrument. Better is to remove this, since the instrument setting is handled by the appropriate instrument config files.
- `"contents"` is missing the `"pageno"` setting. This is what causes the crash. I'll add an error message for this.

In general it is better to create a config that only has the changes you need, so everything else will default to the correct values. `chordpro --print-delta-config` may be helpful.

**Comment by jzbor** [comment]
Thanks a lot! It works how it should now. I will move my config to being a delta of the default config. One slightly unrelated question: How do I get rid of the boxes around the song titles in the table of contents?

**Comment by sciurius** [comment]
I don't see any boxes...
[saitensprung.pdf](https://github.com/ChordPro/chordpro/files/7577360/saitensprung.pdf)

**Comment by jzbor** [comment]
Strange this is what I get (only applying your tips to the existing config
[test.pdf](https://github.com/ChordPro/chordpro/files/7614622/test.pdf)
)

**Comment by sciurius** [comment]
I see you are using PDF::Builder instead of PDF::API2. PDF::Builder supplies a border by default (or by mistake).

I'll file an issue.

**Comment by jzbor** [comment]
Thanks a lot for your support. I am closing this issue now, as it is resolved. I have not verified the fix for the border thing, but looks like it got fixed pretty quickly and I'll just wait for it to get pushed as an update.

**Comment by sciurius** [comment]
Thanks.

While PDF::Builder aims at being a plugin replacement for PDF::API2 there are some small differences.
If you stumble upon visual issues like this, can you try PDF::API2 instead of PDF::Builder to see if it is in ChordPro or in the library?

To facilitate this I've added a config property `pdf.library` that can be set to `"PDF::API2"`, `"PDF::Builder"`, or left empty `""` (ChordPro will use whatever is available).

**Comment by PhilterPaper** [comment]
In PDF::Builder, on GitHub, Annotation.pm has been updated to default to "no border". You can update your copy from that repository, or just edit line 41 to change `0 0 1` to `0 0 0` (the rest of the changes are just POD and comments). As far as a formal release of PDF::Builder (3.024), I'm expecting that no earlier than late December, probably late January.
