### ISSUE TITLE
Latex/ Template - need some discussion/feedback

### ISSUE THREAD

**Issue by JoeRu** [ChordPro/chordpro#210]
Hi @sciurius ,

i did some design over Latex - but figured it can be used as any output. So - still i'm in the middle of developing it - i would really like to discuss this way to go; as i'm sort of stuck in the design decision.... 
It adds a dependency to the perl template-toolkit - which is sure no small thing to do, but gives a lot of flexibility.

Working-State - This commit pretty much work and creates songs Latex in that way. Still all available Latex-packages are pretty "old" or "mature"...
New dependencies:
use Template;
use LaTeX::Encode;

https://github.com/JoeRu/chordpro/commit/8dd134418f335003b7231abfd3ea76839475a8ec

Some questions:
1) Should I keep it "LaTex" specific - while it would be very easy to template any textual output later on?
2) It needs some config-Layer - especially - on where to read the templates in default - I didn't had a look into config yet - suggestions on this?

Any feedback is welcome and appreciated.

**Comment by sciurius** [comment]
There was a LaTeX backend for ChordPro once, but I stalled it a long time ago. Maybe it is worth to take a look?
You'll need to check out R0_65 (commit 41c8ca689716c022c4ee3064e0b36bb17e19fdab) for the 'latest' version.
(You'll notice there was also a LilyPond experiment.)

As for the dependency on `Template`: personally I do not mind but given how you currently use it I would say it is not really necessary. It just wraps lines which you can easily code otherwise. For small, textual substitutions I would recomment `String::Interpolate::Named`, which is already part of the ChordPro requirements.

For config sections, I would propose the root `"latex"` similar to `"pdf"`. Likewise you can use `"markdown"` for your Markdown backend.

**Comment by JoeRu** [comment]
hmm - the main issue with `LaTeX` is - you can do things quite diverse - if it is codess this hard - it will leave not much choices on howto export it (or which Tex-Package to take). There is a lot of variances in howto produce a songbook; this should be let to the users – and the templates – small as they were, are more like a suggestion on how to work with it.
But I will check on `String::Interpolate::Named` – maybe its sufficient.

i will check on the history as well. Thanks.

**Comment by JoeRu** [comment]
Hi @sciurius,
some requests / discussions - sort of -
1) I do need to see the requirement to have "multline"-comments. So i would request a `{begin_of_comment}` and `{end_of_comment}`? What do you think?

2) For Markdown and sort of some LaTeX export it would be nice to have ABC, Lillypond and Grid as graphics to export / include - i did see some sort of coding to export this as graphics for PDF-Export - so - the question is to make use of it and howto - or maybe to restructure code to use it in general?

**Comment by sciurius** [comment]
Shall we move this to ChordPro@groups.io for discussion?
