### ISSUE TITLE
User Community

### ISSUE THREAD

**Issue by sciurius** [ChordPro/chordpro#23]
@topchyan and others have asked: Is there a user group where we can ask questions, share ideas and best practices?

The current answer is no. But it would be great it there was a user forum or mailing list.

This issue is a place to gather ideas and suggestions on how we can get such a community started.

**Comment by topchyan** [comment]
I created this discussion page here: https://groups.google.com/forum/#!forum/chordpro.
If, for whatever reason it doesn't work as expected -- there's is more than one way to do it.

**Comment by sciurius** [comment]
Great. I have added a "Support" topic to the wiki/documentation and included the groups page.

**Comment by sciurius** [comment]
I'll leave this open so other people can see it.

**Comment by sciurius** [comment]
Would it be an option to move this group to groups.io ?

**Comment by topchyan** [comment]
If it is better than existing I'm all for that. I think groups.io has some instructions how to migrate. Let me notify all and ask if there are objections.

**Comment by SirElismyer** [comment]
I've never used groups.io but I'm always happy to learn something new.

**Comment by topchyan** [comment]
I followed directions from groups.io sending them the initial email, but so
far no reaction.
I thought transfer of this group over to groups.io would be more
straightforward.
On their page there's also a bit of text, suggesting that info from Google
Groups may not be transferable due to some kind of a bug.
So, I'm a bit hesitant now.
