### ISSUE TITLE
Keyboard chords can't be defined and there are non per default

### ISSUE THREAD

**Issue by nomike** [ChordPro/chordpro#234]
## Describe the bug
When using "instrument": "keyboard" no chords are defined per default and using any chord results in an error like this:

```plaintext
"test.cho": No chord diagram defined for "C" (skipped)
```

If you try to define it, chordpro produces multiple errors:

```plaintext
Use of uninitialized value $base in numeric gt (>) at /usr/local/share/perl/5.34.0/App/Music/ChordPro/Chords.pm line 314.
Use of uninitialized value $base in concatenation (.) or string at /usr/local/share/perl/5.34.0/App/Music/ChordPro/Chords.pm line 315.
Use of uninitialized value in warn at /usr/local/share/perl/5.34.0/App/Music/ChordPro/Config.pm line 383.
```

### To Reproduce
Download and extract the attached test case and run make.

### Expected behavior
It should be possible to define new chords.
All the common chords should be defined out of the box (they probably where if defining chords weren't broken).

### Attachments
[piano.tar.gz](https://github.com/ChordPro/chordpro/files/9274158/piano.tar.gz)

## System information
 - OS: Ubuntu 22.04 LTS
 - Where did you get ChordPro from? GitHub

 - ChordPro version: 5.987
 - Perl version: v5.34.0

**Comment by sciurius** [comment]
This is slightly related to issue #233.

The easy part: Defining chords fails since you didn't include the `"base"` in the definition. This should have been optional but somehow it slipped through.

The hard part: The built-in chords are for 6 string EADGBE tuned guitar in common notation only. So there are no predefined chords for keyboard. Fortunately it is trivial to derive the keys from the chord, provided it is a common chord (i.e. major, minor. 7th, maj7, minor7, aug, dim, sus4m and half-dim). Unfortunately, the chord parser does not know that the diagram writer knows how to deal with the chord. And since the chord parser does not know the chord you get the error message.

This is now fixed in git.

Thanks for reporting this.

**Comment by nomike** [comment]
Thanks for the very quick fix.

I found a few other glitches with keyboard support and raised separate tickets for them.
