### ISSUE TITLE
Include perl-doc as a dependency or prerequisite (Linux)

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#263]
I finally got around to finding out why `chordpro --manual` was showing me lines starting `=head1` and so forth.

Turns out I need the `perl-doc` package, which makes it all work nicely and look clearer!

Should this be a dependency in the code, or at least an entry in [Prerequisites](https://www.chordpro.org/chordpro/chordpro-install-on-linux/) documentation?

**Comment by sciurius** [comment]
The missing module is `Pod::Usage`, which has been standard part of the perl core for 20 years or so. It is unfortunate that some package maintainers think to gain anything by moving this module to a different package.
I can not add a dependency on `perl-doc` since that is a platform-specific package. I will add a dependency on `Pod::Usage` so it will be pulled in when necessary.

But actually we need a volunteer to build and maintain ChordPro packages for popular linux platforms.
