### ISSUE TITLE
Feature request: Put tab to the right of words/chords

### ISSUE THREAD

**Issue by fechdj1** [ChordPro/chordpro#278]
Got no idea if this is possible and maybe it's a stupid idea but here goes :-)

I've got a couple of songs where there is a little guitar fill at the end of a line.
It'd be great to be able to add the fill (in tablature) to the right hand side of the words/chords.

Cheers

**Comment by sciurius** [comment]
You could try to work with two columns but you'll have to deal with the left and right part separately.
I have something in the works that allow placement of images at the right side of the page, anchored to the lyrics line. This would require turning your tab or annotations into an image.

Synchronized columns and tab positions are interesting suggestions but not easily implemented.

**Comment by gwyndaf** [comment]
I'd considered the possibility of columns but

a) the source file would no longer be human-readable in a meaningful way

b) differences in line spacing for different elements would make proper alignment difficult (possibly the synchronisation difficulty you mention)

c) it might reduce compatibility and not replicate effectively in other software that handles ChordPro format (e.g. Mobile Sheets), e.g. if BVs end up displayed at the end of the song.

For me, tabs would be a stylistic 'nice to have' rather than essential feature, so low priority, particularly if there's no straightforward way to implement.

**Comment by sciurius** [comment]
With the latest dev, you can do things like this.

![scrot20231113000942](https://github.com/ChordPro/chordpro/assets/1118804/b86697f8-4a48-4894-a68e-98cd55a9a9b9)

````
{t: riff}

[A]Hello, [Bm]World! Come and join in
{image id=riff anchor=line x=50% scale=60%}
[A]Hello, [Bm]World! Come and join in

[A]Hello, [Bm]World! Come and join in
{image id=riff2 anchor=line x=50% scale=60%}
[A]Hello, another [Bm]World!  Come and join in


{start_of_abc id=riff}
X:1
K:Em
a b c d
{end_of_abc}
{start_of_abc id=riff2}
X:1
K:Em
d c a b
{end_of_abc}
````

**Comment by sciurius** [comment]
Can we consider this closed?
