### ISSUE TITLE
How to render a minor chord with a flat 9?

### ISSUE THREAD

**Issue by JohannesWiesner** [ChordPro/chordpro#332]
I would like to render the chord notation for [Fmb9] but Chordpro doesn't put the b9 in superscript. It also seems from the docs that this extension is not provided (https://www.chordpro.org/chordpro/chordpro-chords/)?

**Comment by sciurius** [comment]
By default the chord names are shown as plain strings. You can change this with a [format string](https://www.chordpro.org/chordpro/chordpro-configuration-format-strings/#chord-format-string).

The list of extensions in the docs you refer to is slightly misleading, since in that list qualities are included in the extensions. You'll find `mb9` under [Extensions for minor chords](https://www.chordpro.org/chordpro/chordpro-chords/#extensions-for-minor-chords).
