### ISSUE TITLE
Chorus recall tag format issue when label is also present

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#372]
I often refer back to the previous chorus, to save space, which works nicely. I use a custom `tag` for clarity.

_Very_ occasionally, I also have a label on the chorus recall.

I've just noticed (with dev v. 6.050_044) that if a chorus recall also has a label, its tag formatting seems to get ignored, and looks like it's reverting to the basic/lyric text font, rather than using `comment_box` (my chosen base style for the tag).

Sample files: 
[Chorus recall font.zip](https://github.com/ChordPro/chordpro/files/15282419/Chorus.recall.font.zip)

It's most noticeable in the custom format PDF, but even using defaults (plus included config) still shows differences between tag without label, and tag with label.

**Comment by gwyndaf** [comment]
Just confirming that behaviour is as expected with release version 6.050. With custom config:
![Screenshot from 2024-05-11 13-31-32](https://github.com/ChordPro/chordpro/assets/1415754/047143d1-99ad-4eea-874b-2b7cf1aed798)

**Comment by sciurius** [comment]
This is a result from the issue#367 fix. Repeat chorus needed an additional adjustment.
Thanks, fixed in 6.050_048.

FYI: I wrapping up the current developments (which a.o. include the new JSON parser) and will release 6.060 soon. My intention is to continue working on the extended chord formatting (what we called the 'parens' branch) after the release.

**Comment by gwyndaf** [comment]
That works nicely with 6.050_048, and thanks for update on extended formatting.
