### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by topchyan** [ChordPro/chordpro#38]
Would it be possible to provide a way to create clickable (hyper)links or links to local files in PDF?
This can help interactively launch sound clips from YouTube and similar places.
If a link gets stored somewhere in metadata, it could be made available in the body of the page, perhaps?

**Comment by sciurius** [comment]
Technically, yes. But there are some details to tackle. For example, where should the link be placed on the page and how should it look (a link icon of some sort).
Linking to local files has limited use, since it won't work anymore when you give the PDF to someone else. Including files would be an option.

I'd suggest to take this to the forum for discussion.

**Comment by AnniePerson** [comment]
How about using Sciurius' PDLink tool? https://github.com/sciurius/pdflink
I use it regularly and it works fine. Alas not many PDF readers support links.

**Comment by ad-si** [comment]
How about simply supporting it in comments. For consistency the code could be like in markdown:

```
{comment Open song [in spotify](spotify:track:0sBSHslJg4VOtmv8hLP9o5) }
```

**Comment by sciurius** [comment]
This is supported as Pango markup by using Text::Layout 0.025 and later.
