### ISSUE TITLE
Apparent slowdown in processing

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#391]
Just flagging an apparent slowdown in processing time (Linux, Debian Testing).

For example, my book of ~200-songs now takes 600+ seconds to process, as opposed to about 150 seconds previously, while one-off songs take a noticeable time (2-3 secs), rather than being near-instantaneous.

Noticeable since dev version 6.050_074 (and still occurring with _081), but it might have arisen earlier - I hadn't updated for a few weeks prior to that.

I'm sure there are many factors involved, but it seems to be fairly general, and not caused by one 'rogue' song in my collection.

**Comment by sciurius** [comment]
The biggest part of the slowdown is caused by adding debug info to the PDF. This will disappear when ChordPro is released. As of 6.050_082 you can set `debug.runtimeinfo` to `-1` to suppress it.

Also, there is a slight increase (on my system about 0.5 second) per run due to the new config processing and font processing. I've discovered some problems with the config handling but I rather not fix this before 6.060.

Using a 109 song songbook, displaying chords, suppressing debug info:
* 6.050: 13.3 secs, pdf size = 1402064
* 6.050_082: 13.6 secs, pdf size = 1473391

The PDF is bigger since ChordPro now uses embedded TrueType fonts instead of the built-in corefonts.

I hope this takes your worries away...

**Comment by gwyndaf** [comment]
Thanks Johan. Really just sharing the observation for information more than a concern, but sounds like it's a known part of work-in-progress development.

`debug.runtimeinfo -1` tweak neatly speeds things up and reduces PDF sizes :)

**Comment by sciurius** [comment]
As of 6.050_083 you must set debug.runtimeinfo to `0` to suppress it.
