### ISSUE TITLE
Cannot install on Kubuntu 24.04

### ISSUE THREAD

**Issue by TheMaddScientist** [ChordPro/chordpro#396]
I have a relatively normal install of Kubuntu 24.04, including Steam and Wine. When I attempted to run the cpan installation, after installing prerequisites, I got a plethora of errors. The attached file is the dump from about the third try. I have installed chordpro on numerous previous versions of UbuntuStudio with no issues, so this was rather surprising.

[chordprofail.zip](https://github.com/user-attachments/files/16324971/chordprofail.zip)

**Comment by sciurius** [comment]
Sorry to hear you encounter install problems.
At first glance it looks as if the `make` program is missing. Can you verify? You'll also need gcc and g++.

Also, there are (should be) pre-built packages available for many of the prerequisites. It is worth trying these instead of building everything from scratch. 

In particular:
libpdf-api2-perl
libobject-pad-perl
libjavascript-quickjs-perl

**Comment by TheMaddScientist** [comment]
Thank you, Johan. I installed make, gcc, and g++, plus the recommended
other packages with them and everything worked. Apparently Kubuntu no
longer comes with make, gcc, and g++ standard any more. You may want to
update your install instructions to include make, gcc, and g++ as
prerequisites.

Thanks again,
Damien

**Comment by sciurius** [comment]
Great to hear it's working now. I've updated the docs, please see 
https://www.chordpro.org/beta/chordpro-install-on-linux/
