### ISSUE TITLE
Decapo doesn't change use of the `capo` value in `pdf.formats`

### ISSUE THREAD

**Issue by edonv** [ChordPro/chordpro#447]
## Describe the bug
When I use the `--decapo` option (or in config), the output's uses of `%{capo}` in `pdf.formats` still have the original capo value.

### To Reproduce
1. Set `pdf.formats.title.title` to something that uses `%{capo}` (i.e. `["", "%{title} - %{capo}", ""]`).
2. Try outputting a `cho` file with a `capo` directive that isn't `0` (i.e. `2`) to PDF with the `--decapo` option.
3. Check title section of outputted PDF.

### Expected behavior
The header of the front page of the PDF should be "{title} - 0", but instead its something like "{title} - 2".

## System information
 - OS: macOS Sonoma 14.5
 - Where did you get ChordPro from? macOS build

 - ChordPro version: 6.060
 - Perl version: 5.30.3

## Additional context
- It'd be great if this could also update tabs via RegEx replacing
    - something like `/(\d+)/g`, then iterating through each match, casting to integer, adding/subtracting transposition/capo value, replace. and if the new integer value has a different count of digits, remove/insert that number of dashes from matching index in line from other lines of tab.

**Comment by sciurius** [comment]
Thanks. Fixed in 6.060_118.

As for transposing tabs there are several reasons why this is not a good idea.
* The TAB format is not formally defined and may contain numeric information that is not string positions;
* Tab sections are used for arbitrary info with numbers that should not be tampered with;
* Transposing a couple of semitones is (on a stringed instrument) not just a matter of shifting everything up or down - it involves using different positions on higher/lower strings as well.

**Comment by edonv** [comment]
Thanks! And re: tabs, that makes sense. Understood!
