### ISSUE TITLE
Directives for Bridge, Pre-Chrous, Instrumentals, Tags, Endings

### ISSUE THREAD

**Issue by wpmjones** [ChordPro/chordpro#46]
I am brand new to ChordPro (setting up all of our chord charts for church in MobileSheets).  Unless I'm missing it, I'm a bit surprised to see no directives for bridges, pre-choruses, endings, etc.  Any tips for me?

**Comment by sciurius** [comment]
Welcome to ChordPro.

You can use `{comment}` directives to mark sections. For example:

    {comment Bridge}
    Halleluyah
    
    {start_of_chorus}
    ....

ChordPro recognises directives to mark sections, e.g. `{start_of_bridge}`, where "bridge" can be anything. A matching `{end_of_bridge}` is necessary, of course.
However, there are currently no styles associated with these directives, so they do nothing.

Would it be useful to add an option so that

    {start_of_bridge}

is automatically rendered as

    {comment Bridge}

Shall we take this thread to the mailing list? Its a better place to discuss features and usage.

**Comment by sciurius** [comment]
Implemented as of 2018.
