### ISSUE TITLE
I can not run program in Linux Mint 19

### ISSUE THREAD

**Issue by KeyJoo** [ChordPro/chordpro#57]
# ChordPro in Linux Mint 19

Hi there! I installed the program **GUI version**. ([Guide for Linux](https://www.chordpro.org/chordpro/ChordPro-Install-on-Linux.html))

1. `sudo cpan install wxchordpro` 
2. `wxchordpro`

:warning: But result is not good. Run was failed.

![screenshot from 2018-12-03 14-10-21](https://user-images.githubusercontent.com/21124057/49370459-3b80e400-f705-11e8-967d-cef7e216021a.png)

## Text mode

To see full [installation log](https://gist.githubusercontent.com/KeyJoo/0a88c3b4c098f2961e4d8e8cb3d7f6eb/raw/88e8b064b20c752cf0931a316fdfccd5288dea28/chordpro-install-log.md)

## Question

:dart: Can you help me how fix it?

**Comment by neophytte** [comment]
cpan -i Wx
see: http://www.wxperl.it/p/download.html

-------------------------------
J. R. Mortimer

----- Original Message -----
From: "ChordPro/chordpro" 
To:"ChordPro/chordpro" 
Cc:"Subscribed" 
Sent:Mon, 03 Dec 2018 03:43:32 -0800
Subject:[ChordPro/chordpro] I can not run program in Linux Mint 19
(#57)

CHORDPRO IN LINUX MINT 19

	Hi there! I installed the program GUI VERSION. (Guide for Linux [1]) 

	sudo cpan install wxchordpro 

	⚠️ But result is not good. Run was failed. 

	 [2] 

TEXT MODE

	To see full installation log [3] 

	Can you help me how fix it? 

	—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub [4], or mute the
thread [5]. 

Links:
------
[1] https://www.chordpro.org/chordpro/ChordPro-Install-on-Linux.html
[2]
https://user-images.githubusercontent.com/21124057/49370459-3b80e400-f705-11e8-967d-cef7e216021a.png
[3]
https://gist.githubusercontent.com/KeyJoo/0a88c3b4c098f2961e4d8e8cb3d7f6eb/raw/88e8b064b20c752cf0931a316fdfccd5288dea28/chordpro-install-log.md
[4] https://github.com/ChordPro/chordpro/issues/57
[5]

**Comment by sciurius** [comment]
The build fails on the wxWidgets library. Building wxWidgets can be a bit
tricky, although it ought to give no problems on a decent Linux
distribution. 

I am not familiar with Linux Mint, but there should be a wxWidgets library
in the repository. Can you try something similar to

    sudo apt install wxwidgets
    sudo apt install libwx-perl
