### ISSUE TITLE
How can I uninstall?

### ISSUE THREAD

**Issue by GiancarloGomez** [ChordPro/chordpro#58]
Is there a way to uninstall?

**Comment by sciurius** [comment]
That depends on how you installed ChordPro. Let us know.

Can you tell us why you want to stop using ChordPro?

**Comment by GiancarloGomez** [comment]
I installed as per your instructions on my Mac.

Don’t need it as the file I downloaded says it was ChordPro but it really
does not render as I needed. Anyways, no need for it thanks.

Thank you,
Giancarlo Gomez
http://giancarlogomez.com

From: Johan Vromans <notifications@github.com> <notifications@github.com>
Reply: ChordPro/chordpro
<reply@reply.github.com>
<reply@reply.github.com>
Date: December 3, 2018 at 3:02:45 PM
To: ChordPro/chordpro <chordpro@noreply.github.com>
<chordpro@noreply.github.com>
Cc: Giancarlo Gomez <giancarlo.gomez@gmail.com> <giancarlo.gomez@gmail.com>,
Author <author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [ChordPro/chordpro] How can I uninstall? (#58)

That depends on how you installed ChordPro. Let us know.

Can you tell us why you want to stop using ChordPro?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChordPro/chordpro/issues/58#issuecomment-443850385>,
or mute
the thread

**Comment by sciurius** [comment]
Thanks for providing the file. There are many programs around that implement ChordPro-like song data and most of them are incompatible with the 'standard' version as implemented by the ChordPro program discussed here.

Nevertheless, the song can be made to render well with just a couple of minor changes. See the attachments. The song uses Nashville Number Notation for chords, which is supported by ChordPro but you must add `--config nashville` to the command line.

In `joy.txt` I added `{columns:2}` at the top, and used `{column_break}` instead of `{start_column}` / `{end_column}`.

With some more changes -- see joy2 and joy3.
[joy.pdf](https://github.com/ChordPro/chordpro/files/2645492/joy.pdf)
[joy.txt](https://github.com/ChordPro/chordpro/files/2645493/joy.txt)
[joy2.pdf](https://github.com/ChordPro/chordpro/files/2645494/joy2.pdf)
[joy2.txt](https://github.com/ChordPro/chordpro/files/2645495/joy2.txt)
[joy3.pdf](https://github.com/ChordPro/chordpro/files/2645496/joy3.pdf)
[joy3.txt](https://github.com/ChordPro/chordpro/files/2645497/joy3.txt)

**Comment by GiancarloGomez** [comment]
Cool thanks
