### ISSUE TITLE
Label in {chorus: foobar} causes layout to be indented

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#79]
Seems like the layout gets indented if there's an argument supplied to the {chorus} directive to create a label. IIRC previous versions seemed to ignore the label. Now it's included in the layout, but with the effect of everything being indented.

- {chorus} gives normal layout
- {chorus:} gives normal layout
- {chorus: } gives normal layout
- {chorus:x} gives slightly indented layout (about same as left margin)
- {chorus:xxxxxxxx} gives very indented layout

So, it looks like the amount of indentation might be related to the number of characters in the label argument.

**Comment by ChordPro** [comment]
Your observation is right: the amount of indentation corresponds to the width of the label.

By default, when any section (e.g., verse, or chorus) uses a label, the song will be indented with the width of the widest label, and the labels are printed in the margin thus created. This turned out not to be correctly implemented for the `{chorus: label}` case. This has been fixed now in git.

See also: https://www.chordpro.org/chordpro/ChordPro-Configuration-PDF.html#labels

**Comment by gwyndaf** [comment]
Great, thanks!
